'use client';
import {useState,useEffect} from 'react';
import {Play,RotateCcw,Square,Search} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import type {SearchJob} from '@/lib/types';
export default function SearchJobsPanel({jobs,busy,mutate}:{jobs:SearchJob[];busy:boolean;mutate:(action:string,payload:Record<string,unknown>,message:string)=>void}){
 const [clock,setClock]=useState(()=>Date.now());useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
 return <div className="jobs-list">{!jobs.length&&<section className="content-card empty-state"><Search size={30}/><h3>No searches yet</h3><p>Choose Generate leads to save your criteria and create a resumable search.</p></section>}{jobs.map(j=>{const criteria=JSON.parse(j.criteria) as {industry:string;state:string;city:string;type:string};return <section className="content-card job-card" key={j.id}><div className="panel-heading"><div><h2>{criteria.industry} · {j.provider}</h2><p>{[criteria.city,criteria.state].filter(Boolean).join(', ')} · {criteria.type}</p></div><span className="status">{j.status}</span></div><Progress value={Math.min(100,j.processed/j.requested*100)}/><p>{j.processed.toLocaleString()} / {j.requested.toLocaleString()} records processed · {j.imported.toLocaleString()} added · {j.skipped} duplicates</p>{j.error&&<div className="notice">{j.error}{j.status==='Retrying'&&` Next attempt after ${new Date(j.nextRunAt).toLocaleString()}`}</div>}<div className="card-actions">{['Queued','Running','Retrying'].includes(j.status)&&<button className="btn primary" disabled={busy||Date.parse(j.nextRunAt)>clock||j.leaseUntil>clock} onClick={()=>mutate('runJob',{id:j.id},'Batch processed')}><Play size={15}/>Process next batch</button>}{j.status==='Failed'&&<button className="btn" disabled={busy} onClick={()=>mutate('retryJob',{id:j.id},'Search queued')}><RotateCcw size={15}/>Retry from checkpoint</button>}{!['Completed','Cancelled'].includes(j.status)&&<button className="btn" disabled={busy} onClick={()=>mutate('cancelJob',{id:j.id},'Search cancelled')}><Square size={14}/>Cancel</button>}</div><small>Progress is saved after each batch. Your configured scheduler can continue when this page is closed.</small></section>;})}</div>;
}
