'use client';
import {useState} from 'react';
import {Users,ShieldCheck,Database,History,Settings2,ExternalLink} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {WorkspaceData} from '@/lib/types';
type Props={data:WorkspaceData;busy:boolean;mutate:(action:string,payload:Record<string,unknown>,message:string)=>void;children:React.ReactNode};
export default function SettingsPanel({data,busy,mutate,children}:Props){
 const [email,setEmail]=useState(''),[role,setRole]=useState('member');const admin=['owner','admin'].includes(data.access.role);
 return <Tabs defaultValue="general" className="settings-tabs"><TabsList><TabsTrigger value="general"><Settings2 size={15}/>General</TabsTrigger><TabsTrigger value="sources"><Database size={15}/>Integrations</TabsTrigger><TabsTrigger value="users"><Users size={15}/>Users & roles</TabsTrigger><TabsTrigger value="audit"><History size={15}/>Audit history</TabsTrigger></TabsList>
 <TabsContent value="general">{children}</TabsContent>
 <TabsContent value="sources"><div className="content-grid">{data.providers.map(p=><section className="content-card" key={p.id}><span className={'status '+(p.configured?'status-interested':'')}>{p.configured?'Configured':'Credentials required'}</span><h2>{p.name}</h2><p>{p.description}</p><small>{p.credentials.join(' · ')}</small><p>Available lead types: {p.types.join(', ')}</p></section>)}<section className="content-card"><MailStatus configured={data.connections.email} title="SendGrid"/><p>API delivery, signed delivery events and signed Inbound Parse replies. Live sending remains gated until domain and public callback/unsubscribe access are verified.</p><small>SENDGRID_API_KEY · SENDGRID_EVENT_PUBLIC_KEY · SENDGRID_PARSE_PUBLIC_KEY</small></section><section className="content-card"><h2>Enrichment from Solara</h2><p>BatchData and DataZapp require paid contact matching access. Their account response contracts must be validated before mapping results to people. Google Geocoding normalizes addresses; it does not supply emails.</p><a className="text-button" href="https://www.datazapp.com/email-append" target="_blank" rel="noreferrer">Provider details <ExternalLink size={14}/></a></section><section className="content-card"><h2>Candidate access</h2><p>Indeed and ATS candidate records require approved employer/partner access. Adzuna supplies job openings, not applicants. Use authorized candidate imports or a licensed ATS adapter until access is confirmed.</p><a className="text-button" href="https://docs.indeed.com/" target="_blank" rel="noreferrer">Indeed partner documentation <ExternalLink size={14}/></a></section></div></TabsContent>
 <TabsContent value="users"><section className="content-card"><h2>Workspace access</h2><p>Owner and administrators manage settings. Members manage leads and campaigns. Viewers have read-only access. Site sharing must also allow the same email; saving a member does not send an invitation.</p>{admin?<><form className="member-form" onSubmit={e=>{e.preventDefault();mutate('saveMember',{email,role},'Member saved');}}><input type="email" required aria-label="Member email" placeholder="colleague@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><Select value={role} onValueChange={setRole}><SelectTrigger aria-label="Member role"><SelectValue/></SelectTrigger><SelectContent>{(data.access.role==='owner'?['admin','member','viewer']:['member','viewer']).map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select><button className="btn primary" disabled={busy}>Save access</button></form><Table><TableHeader><TableRow><TableHead>USER</TableHead><TableHead>ROLE</TableHead><TableHead>STATUS</TableHead><TableHead/></TableRow></TableHeader><TableBody>{data.members.map(m=><TableRow key={m.id}><TableCell>{m.email}<small className="block">{m.name}</small></TableCell><TableCell>{m.role}</TableCell><TableCell>{m.status}</TableCell><TableCell>{m.role!=='owner'&&m.userId!==data.access.userId&&<button className="text-button" disabled={busy||m.status==='Disabled'} onClick={()=>mutate('disableMember',{id:m.id},'Member disabled')}>Disable</button>}</TableCell></TableRow>)}</TableBody></Table></>:<div className="notice">User management is available to the workspace owner and administrators.</div>}</section></TabsContent>
 <TabsContent value="audit"><section className="content-card"><h2>Audit history</h2><p>Latest 200 recorded workspace actions. Audit records are read-only in the application and do not contain API keys or message bodies.</p>{admin?<><Table><TableHeader><TableRow><TableHead>TIME</TableHead><TableHead>USER</TableHead><TableHead>ACTION</TableHead><TableHead>DETAILS</TableHead></TableRow></TableHeader><TableBody>{data.audit.map(a=><TableRow key={a.id}><TableCell>{new Date(a.createdAt).toLocaleString()}</TableCell><TableCell>{a.actorEmail}</TableCell><TableCell>{a.action}</TableCell><TableCell>{a.summary}</TableCell></TableRow>)}</TableBody></Table>{!data.audit.length&&<p>No recorded actions yet.</p>}</>:<div className="notice">Audit history is available to administrators.</div>}</section></TabsContent>
 </Tabs>;
}
function MailStatus({configured,title}:{configured:boolean;title:string}){return <><span className="status">{configured?'Configured':'Credentials required'}</span><h2><ShieldCheck size={17} className="inline"/> {title}</h2></>;}
