'use client';
import {useCallback,useEffect,useState} from 'react';
import type {SetupGroup,SetupField} from '@/lib/setup/catalog';
type Field=SetupField&{configured:boolean;source:string;value:string};
type Group=Omit<SetupGroup,'fields'>&{fields:Field[]};
export default function SetupPanel(){
 const [groups,setGroups]=useState<Group[]>([]),[revision,setRevision]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async(message?:string)=>{try{const response=await fetch('/api/setup',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setGroups(data.groups);setRevision(data.revision);setError('');if(message)setNotice(message);}catch(error){setError(error instanceof Error?error.message:'Unable to load settings');}},[]);
 useEffect(()=>{let cancelled=false;fetch('/api/setup',{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);return data;}).then(data=>{if(!cancelled){setGroups(data.groups);setRevision(data.revision);}}).catch(()=>{if(!cancelled)setError('Unable to load settings');});return()=>{cancelled=true;};},[]);
 return <div className="setup-dashboard"><div className="notice">Saved secrets stay encrypted and are never shown again. Leave a secret blank to keep it; Clear disables that setting. <a className="text-button" href="/setup">Open standalone setup</a></div>{error&&<div className="error-banner" role="alert">{error}<button onClick={()=>void load()}>Retry</button></div>}{notice&&<p role="status" className="notice">{notice}</p>}<div className="setup-grid">{groups.map(group=><ConnectionForm key={group.id+revision} group={group} revision={revision} reload={load}/>)}</div></div>;
}
function ConnectionForm({group,revision,reload}:{group:Group;revision:string;reload:(message?:string)=>Promise<void>}){
 const [values,setValues]=useState<Record<string,string>>({}),[confirmSwitch,setConfirmSwitch]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function perform(action:'save'|'test'|'restoreSupabase'|'initializeSupabase'){
  setBusy(true);setMessage('');try{const response=await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,group:group.id,values,revision,confirmSwitch})});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage(result.message);setValues({});if(action!=='test'){await reload(result.message);}}catch(error){setMessage(error instanceof Error?error.message:'Request failed');}finally{setBusy(false);}
 }
 return <section className="content-card setup-card"><h2>{group.title}</h2><p>{group.description}</p><form onSubmit={e=>{e.preventDefault();void perform('save');}} className="setup-form">{group.fields.map(field=><label className="field" key={field.key}><span>{field.label}</span>{field.kind==='boolean'?<select value={values[field.key]??field.value??'false'} onChange={e=>setValues({...values,[field.key]:e.target.value})}><option value="false">Disabled</option><option value="true">Enabled</option></select>:<div className="setup-input-row"><input type={field.secret?'password':'text'} autoComplete="off" value={values[field.key]??(field.secret?'':field.value)} placeholder={field.secret&&field.configured?'Saved  -  leave blank to keep':'Not configured'} onChange={e=>{const next={...values};if(field.secret&&!e.target.value)delete next[field.key];else next[field.key]=e.target.value;setValues(next);}}/><button type="button" className="text-button" disabled={busy||field.required} onClick={()=>setValues({...values,[field.key]:''})}>Clear</button></div>}<small>{values[field.key]===''?'Will be disabled on save':field.configured?`Configured  -  ${field.source==='dashboard'?'saved in dashboard':'deployment default'}`:'Not configured'}</small></label>)}{group.id==='supabase'&&<><label className="setup-confirm"><input type="checkbox" checked={confirmSwitch} onChange={e=>setConfirmSwitch(e.target.checked)}/><span>I understand that switching does not move existing leads, campaigns or files. The initial settings database stays connected for recovery.</span></label></>}<div className="card-actions">{group.testable&&<button type="button" className="btn" disabled={busy} onClick={()=>void perform('test')}>Test connection</button>}<button className="btn primary" disabled={busy}>{busy?'Working - ':group.id==='supabase'?'Verify & save connection':'Save settings'}</button>{group.id==='supabase'&&<><button type="button" className="btn" disabled={busy||!confirmSwitch} onClick={()=>void perform('initializeSupabase')}>Initialize empty project & connect</button><button type="button" className="btn" disabled={busy} onClick={()=>void perform('restoreSupabase')}>Restore deployment connection</button></>}</div><p role="status">{message}</p></form></section>;
}
