import {db,addLeads,runtime,now,HttpError} from './server';
import {searchCriteria,availableProviders,fetchProviderPage,ProviderError} from './providers';
import type {SearchJob} from './types';
export async function createSearchJob(user:string,input:unknown){const criteria=searchCriteria.parse(input);const provider=availableProviders(runtime()).find(p=>p.id===criteria.provider);if(!provider?.configured)throw new HttpError(409,'This source needs credentials before it can run.');if(!provider.types.includes(criteria.type))throw new HttpError(400,'This source cannot supply this lead type.');const id=crypto.randomUUID();await db().prepare('INSERT INTO searchJobs (id,owner,provider,criteria,status,requested,nextRunAt,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,user,criteria.provider,JSON.stringify(criteria),'Queued',criteria.limit,now(),now(),now()).run();return{id,message:'Search saved. Process a batch now or let your configured scheduler continue it.'};}
export async function processSearchJob(user:string,id:string){
 const database=db(),time=Date.now();const job=await database.prepare('SELECT * FROM searchJobs WHERE id=? AND owner=?').bind(id,user).first<SearchJob>();if(!job)throw new HttpError(404,'Search job not found');if(['Completed','Cancelled'].includes(job.status))return{message:`Search is ${job.status.toLowerCase()}.`};if(job.status==='Failed')throw new HttpError(409,'Retry this failed search before processing it.');if(Date.parse(job.nextRunAt)>time)throw new HttpError(429,'Provider retry delay has not elapsed.');
 const lock=await database.prepare("UPDATE searchJobs SET status='Running',leaseUntil=?,updatedAt=? WHERE id=? AND owner=? AND status IN ('Queued','Running','Retrying') AND leaseUntil<?").bind(time+60000,now(),id,user,time).run();if(!lock.meta.changes)throw new HttpError(409,'This search is already being processed.');
 try{const criteria=searchCriteria.parse(JSON.parse(job.criteria));const page=await fetchProviderPage(runtime(),criteria,job.cursor,job.requested-job.processed);const current=await database.prepare('SELECT status FROM searchJobs WHERE id=?').bind(id).first<{status:string}>();if(current?.status==='Cancelled')return{message:'Search cancelled before importing this batch.'};
 const imported=await addLeads(user,page.leads);const processed=job.processed+page.leads.length;const complete=page.exhausted||processed>=job.requested;await database.prepare("UPDATE searchJobs SET status=?,processed=?,imported=imported+?,skipped=skipped+?,cursor=?,attempts=0,error='',nextRunAt=?,leaseUntil=0,updatedAt=? WHERE id=? AND owner=? AND status!='Cancelled'").bind(complete?'Completed':'Queued',processed,imported.imported,imported.skipped,page.nextCursor,now(),now(),id,user).run();return{message:`${imported.imported} leads added. Search ${complete?'completed':'saved; more batches remain'}.`};
 }catch(e){const retry=e instanceof ProviderError&&e.retryable&&job.attempts<4;const wait=e instanceof ProviderError?Math.max(e.retryAfter,Math.pow(2,job.attempts)*30):60;const message=e instanceof ProviderError?e.message:'Provider response did not match the documented contract. No cursor was advanced.';await database.prepare("UPDATE searchJobs SET status=?,attempts=attempts+1,error=?,nextRunAt=?,leaseUntil=0,updatedAt=? WHERE id=? AND owner=? AND status!='Cancelled'").bind(retry?'Retrying':'Failed',message,new Date(Date.now()+wait*1000).toISOString(),now(),id,user).run();return{message:`${message} ${retry?'Retry scheduled.':'Review the provider and retry the job.'}`};}
}
