import {database} from '@/db';
import {allowedOrigin} from './request-origin';
import {access,AccessError} from './access';
import type {WorkspaceSettings} from './types';
import {z} from 'zod';
import {STATUSES,normalizeImportedLead} from './domain';
export {getConfiguration as runtime} from './setup/store';
export const db=database;
export class HttpError extends Error {constructor(public status:number,message:string){super(message);}}
export async function owner(){return (await access()).workspaceId;}
export function originCheck(req:Request){if(!allowedOrigin(req.url,req.headers.get('origin'),process.env.APP_URL))throw new HttpError(403,'Origin not allowed');}
export function failure(e:unknown){console.error('Workspace request failed',(e instanceof HttpError||e instanceof AccessError)?e.message:e instanceof Error?e.name:'UnknownError');return Response.json({error:(e instanceof HttpError||e instanceof AccessError)?e.message:e instanceof z.ZodError?e.issues.map(x=>`${x.path.join('.')}: ${x.message}`).slice(0,3).join('; '):'Unable to complete this request. Please retry.'},{status:(e instanceof HttpError||e instanceof AccessError)?e.status:e instanceof z.ZodError?400:503});}
export const now=()=>new Date().toISOString();
const short=z.string().trim().max(300);
export const leadSchema=z.object({id:z.string().uuid().optional(),name:short.min(1),email:z.union([z.string().trim().email().max(254),z.literal('')]).default(''),phone:short.default(''),company:short.default(''),industry:short.min(1),state:short.default(''),city:short.default(''),type:z.enum(['Prospect','Insurance consumer','Insurance agent / agency','Property owner','Candidate','Business','Job opening']).default('Prospect'),skills:z.string().max(3000).default(''),experience:z.string().max(3000).default(''),source:short.min(1).default('Manual entry'),sourceUrl:z.union([z.string().url().max(2000),z.literal('')]).default(''),status:z.enum(STATUSES as [string,...string[]]).default('New'),permission:z.enum(['Unknown','Opted in','Permitted business contact']).default('Unknown'),notes:z.string().max(10000).default(''),address:short.default(''),zip:short.default(''),jobTitle:short.default(''),sourceRef:z.string().max(1000).nullable().optional()});
export const defaultSettings:WorkspaceSettings={senderName:'',senderEmail:'',replyTo:'',postalAddress:'',dailyLimit:100};
export async function getSettings(user:string){const r=await db().prepare('SELECT value FROM settings WHERE owner=?').bind(user).first<{value:string}>();return r?{...defaultSettings,...JSON.parse(r.value) as WorkspaceSettings}:defaultSettings;}
export async function addLeads(user:string,rows:unknown[]){const records=rows.map(r=>leadSchema.parse(normalizeImportedLead(z.record(z.unknown()).parse(r))));let imported=0;for(let offset=0;offset<records.length;offset+=50){const chunk=records.slice(offset,offset+50);const result=await db().batch(chunk.map(l=>db().prepare('INSERT INTO leads (id,owner,name,email,phone,company,industry,state,city,type,skills,experience,source,sourceUrl,status,permission,notes,address,zip,jobTitle,sourceRef,createdAt,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING').bind(crypto.randomUUID(),user,l.name,l.email||null,l.phone,l.company,l.industry,l.state,l.city,l.type,l.skills,l.experience,l.source,l.sourceUrl,l.status,l.permission,l.notes,l.address,l.zip,l.jobTitle,l.sourceRef||null,now(),now())));imported+=result.reduce((n,r)=>n+(r.meta.changes||0),0);}return{imported,skipped:records.length-imported,message:`${imported} leads imported · ${records.length-imported} duplicates skipped`};}
export async function suppress(user:string,email:string,reason:string){if(!email)return;await db().batch([db().prepare('INSERT INTO suppressions (id,owner,email,reason,createdAt) VALUES (?,?,?,?,?) ON CONFLICT(owner,email) DO NOTHING').bind(crypto.randomUUID(),user,email.toLowerCase(),reason,now()),db().prepare("UPDATE leads SET status='Unsubscribed',updatedAt=? WHERE owner=? AND email=?").bind(now(),user,email.toLowerCase())]);}
export async function signature(secret:string,value:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('');}
export function equal(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
