// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const leads=sqliteTable('leads',{
 id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),email:text('email'),phone:text('phone').notNull().default(''),company:text('company').notNull().default(''),industry:text('industry').notNull(),state:text('state').notNull().default(''),city:text('city').notNull().default(''),type:text('type').notNull().default('Prospect'),skills:text('skills').notNull().default(''),experience:text('experience').notNull().default(''),source:text('source').notNull(),sourceUrl:text('sourceUrl').notNull().default(''),status:text('status').notNull().default('New'),permission:text('permission').notNull().default('Unknown'),notes:text('notes').notNull().default(''),resumeKey:text('resumeKey'),createdAt:text('createdAt').notNull(),updatedAt:text('updatedAt').notNull()
},t=>[uniqueIndex('leads_owner_email').on(t.owner,t.email),index('leads_owner_industry_state').on(t.owner,t.industry,t.state),index('leads_owner_created').on(t.owner,t.createdAt)]);
export const industries=sqliteTable('industries',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull()},t=>[uniqueIndex('industries_owner_name').on(t.owner,t.name)]);
export const settings=sqliteTable('settings',{owner:text('owner').primaryKey(),value:text('value').notNull()});
export const campaigns=sqliteTable('campaigns',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),industry:text('industry').notNull(),subject:text('subject').notNull(),body:text('body').notNull(),status:text('status').notNull().default('Draft'),createdAt:text('createdAt').notNull()},t=>[index('campaigns_owner').on(t.owner)]);
export const deliveries=sqliteTable('deliveries',{id:text('id').primaryKey(),owner:text('owner').notNull(),campaignId:text('campaignId').notNull().references(()=>campaigns.id),leadId:text('leadId').notNull().references(()=>leads.id),status:text('status').notNull().default('Queued'),providerId:text('providerId'),error:text('error'),createdAt:text('createdAt').notNull(),sentAt:text('sentAt')},t=>[uniqueIndex('delivery_campaign_lead').on(t.campaignId,t.leadId),index('deliveries_owner_status').on(t.owner,t.status)]);
export const replies=sqliteTable('replies',{id:text('id').primaryKey(),owner:text('owner').notNull(),leadId:text('leadId').notNull().references(()=>leads.id),subject:text('subject').notNull(),body:text('body').notNull(),classification:text('classification').notNull().default('Needs review'),createdAt:text('createdAt').notNull()},t=>[index('replies_owner').on(t.owner)]);
export const suppressions=sqliteTable('suppressions',{id:text('id').primaryKey(),owner:text('owner').notNull(),email:text('email').notNull(),reason:text('reason').notNull(),createdAt:text('createdAt').notNull()},t=>[uniqueIndex('suppression_owner_email').on(t.owner,t.email)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),createdAt:text('createdAt').notNull()});
export const sendLocks=sqliteTable('sendLocks',{owner:text('owner').primaryKey(),expiresAt:integer('expiresAt').notNull(),token:text('token').notNull()});
