import {pgTable,text,integer,bigint,timestamp,uniqueIndex,index} from 'drizzle-orm/pg-core';
export const leads=pgTable('leads',{
 id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),email:text('email'),phone:text('phone').notNull().default(''),company:text('company').notNull().default(''),industry:text('industry').notNull(),state:text('state').notNull().default(''),city:text('city').notNull().default(''),type:text('type').notNull().default('Prospect'),skills:text('skills').notNull().default(''),experience:text('experience').notNull().default(''),source:text('source').notNull(),sourceUrl:text('sourceUrl').notNull().default(''),status:text('status').notNull().default('New'),permission:text('permission').notNull().default('Unknown'),notes:text('notes').notNull().default(''),resumeKey:text('resumeKey'),address:text('address').notNull().default(''),zip:text('zip').notNull().default(''),jobTitle:text('jobTitle').notNull().default(''),sourceRef:text('sourceRef'),createdAt:text('createdAt').notNull(),updatedAt:text('updatedAt').notNull()
},t=>[uniqueIndex('leads_owner_email').on(t.owner,t.email),uniqueIndex('leads_source_identity').on(t.owner,t.source,t.sourceRef),index('leads_owner_industry_state').on(t.owner,t.industry,t.state),index('leads_owner_created').on(t.owner,t.createdAt)]);
export const industries=pgTable('industries',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull()},t=>[uniqueIndex('industries_owner_name').on(t.owner,t.name)]);
export const settings=pgTable('settings',{owner:text('owner').primaryKey(),value:text('value').notNull()});
export const campaigns=pgTable('campaigns',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),industry:text('industry').notNull(),subject:text('subject').notNull(),body:text('body').notNull(),status:text('status').notNull().default('Draft'),createdAt:text('createdAt').notNull()},t=>[index('campaigns_owner').on(t.owner)]);
export const deliveries=pgTable('deliveries',{id:text('id').primaryKey(),owner:text('owner').notNull(),campaignId:text('campaignId').notNull().references(()=>campaigns.id),leadId:text('leadId').notNull().references(()=>leads.id),status:text('status').notNull().default('Queued'),providerId:text('providerId'),error:text('error'),createdAt:text('createdAt').notNull(),sentAt:text('sentAt')},t=>[uniqueIndex('delivery_campaign_lead').on(t.campaignId,t.leadId),index('deliveries_owner_status').on(t.owner,t.status)]);
export const replies=pgTable('replies',{id:text('id').primaryKey(),owner:text('owner').notNull(),leadId:text('leadId').notNull().references(()=>leads.id),subject:text('subject').notNull(),body:text('body').notNull(),classification:text('classification').notNull().default('Needs review'),createdAt:text('createdAt').notNull()},t=>[index('replies_owner').on(t.owner)]);
export const suppressions=pgTable('suppressions',{id:text('id').primaryKey(),owner:text('owner').notNull(),email:text('email').notNull(),reason:text('reason').notNull(),createdAt:text('createdAt').notNull()},t=>[uniqueIndex('suppression_owner_email').on(t.owner,t.email)]);
export const events=pgTable('events',{id:text('id').primaryKey(),createdAt:text('createdAt').notNull()});
export const sendLocks=pgTable('sendLocks',{owner:text('owner').primaryKey(),expiresAt:bigint('expiresAt',{mode:'number'}).notNull(),token:text('token').notNull()});

export const memberships=pgTable('memberships',{id:text('id').primaryKey(),workspaceId:text('workspaceId').notNull(),userId:text('userId'),email:text('email').notNull(),name:text('name').notNull().default(''),role:text('role').notNull().default('member'),status:text('status').notNull().default('Active'),createdAt:text('createdAt').notNull()},t=>[uniqueIndex('membership_workspace_email').on(t.workspaceId,t.email),index('membership_user').on(t.userId)]);
export const auditLogs=pgTable('auditLogs',{id:text('id').primaryKey(),workspaceId:text('workspaceId').notNull(),actorId:text('actorId').notNull(),actorEmail:text('actorEmail').notNull(),action:text('action').notNull(),entityId:text('entityId').notNull().default(''),summary:text('summary').notNull().default(''),createdAt:text('createdAt').notNull()},t=>[index('audit_workspace_time').on(t.workspaceId,t.createdAt)]);
export const searchJobs=pgTable('searchJobs',{id:text('id').primaryKey(),owner:text('owner').notNull(),provider:text('provider').notNull(),criteria:text('criteria').notNull(),status:text('status').notNull().default('Queued'),requested:integer('requested').notNull(),processed:integer('processed').notNull().default(0),imported:integer('imported').notNull().default(0),skipped:integer('skipped').notNull().default(0),cursor:text('cursor').notNull().default(''),attempts:integer('attempts').notNull().default(0),error:text('error').notNull().default(''),nextRunAt:text('nextRunAt').notNull(),leaseUntil:bigint('leaseUntil',{mode:'number'}).notNull().default(0),createdAt:text('createdAt').notNull(),updatedAt:text('updatedAt').notNull()},t=>[index('search_jobs_owner_status').on(t.owner,t.status),index('search_jobs_schedule').on(t.status,t.nextRunAt)]);

export const appConfiguration=pgTable('app_configuration',{name:text('name').primaryKey(),payload:text('payload').notNull(),updatedAt:timestamp('updated_at',{withTimezone:true,mode:'string'}).notNull().defaultNow()});
export const adminLoginAttempts=pgTable('admin_login_attempts',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),resetAt:bigint('reset_at',{mode:'number'}).notNull()});
