ALTER TABLE public."leads" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."leads" FROM anon, authenticated;
ALTER TABLE public."industries" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."industries" FROM anon, authenticated;
ALTER TABLE public."settings" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."settings" FROM anon, authenticated;
ALTER TABLE public."campaigns" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."campaigns" FROM anon, authenticated;
ALTER TABLE public."deliveries" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."deliveries" FROM anon, authenticated;
ALTER TABLE public."replies" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."replies" FROM anon, authenticated;
ALTER TABLE public."suppressions" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."suppressions" FROM anon, authenticated;
ALTER TABLE public."events" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."events" FROM anon, authenticated;
ALTER TABLE public."sendLocks" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."sendLocks" FROM anon, authenticated;
ALTER TABLE public."memberships" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."memberships" FROM anon, authenticated;
ALTER TABLE public."auditLogs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."auditLogs" FROM anon, authenticated;
ALTER TABLE public."searchJobs" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."searchJobs" FROM anon, authenticated;
