import {z} from 'zod';
import {db,owner,originCheck,failure,HttpError,now,leadSchema,addLeads,getSettings,suppress,runtime} from '@/lib/server';
import {sendCampaign} from '@/lib/outreach';
const id=z.string().uuid();
const text=z.string().trim().min(1).max(300);
const classification=z.enum(['Needs review','Interested','Not interested','Question','Unsubscribe']);
function where(user:string,d:any){const clauses=['owner=?'],values:any[]=[user];for(const [key,all] of [['industry','All industries'],['state','All states'],['status','All statuses'],['type','All lead types']]){if(typeof d[key]==='string'&&d[key]&&d[key]!==all){clauses.push(`${key}=?`);values.push(d[key]);}}for(const key of ['city','query','skills']){if(typeof d[key]==='string'&&d[key]){const s='%'+d[key].slice(0,300).replace(/[\\%_]/g,'\\$&')+'%';const columns=key==='query'?['name','email','company']:key==='skills'?['skills','experience']:['city'];clauses.push('('+columns.map(c=>`${c} LIKE ? ESCAPE '\\'`).join(' OR ')+')');values.push(...columns.map(()=>s));}}if(d.ids?.length){const ids=z.array(id).max(1000).parse(d.ids);clauses.push(`id IN (${ids.map(()=>'?').join(',')})`);values.push(...ids);}return{sql:clauses.join(' AND '),values};}
export async function POST(req:Request){try{originCheck(req);const user=await owner();if(Number(req.headers.get('content-length'))>3_000_000)throw new HttpError(413,'Request is too large');const {action,data:d}=z.object({action:z.string(),data:z.record(z.any()).default({})}).parse(await req.json());const database=db();
 if(action==='list'||action==='export'){const w=where(user,d);if(action==='export'){const result=await database.prepare(`SELECT * FROM leads WHERE ${w.sql} ORDER BY createdAt DESC LIMIT 10000`).bind(...w.values).all();return Response.json({leads:result.results});}const page=z.number().int().min(1).max(100000).parse(d.page||1);const [list,count,stats,industry,campaigns,replies,settings]=await Promise.all([database.prepare(`SELECT * FROM leads WHERE ${w.sql} ORDER BY createdAt DESC,id DESC LIMIT 25 OFFSET ?`).bind(...w.values,(page-1)*25).all(),database.prepare(`SELECT COUNT(*) n FROM leads WHERE ${w.sql}`).bind(...w.values).first<any>(),database.prepare("SELECT COUNT(*) total,COALESCE(SUM(status IN ('Interested','Qualified')),0) interested,COALESCE(SUM(status='Contacted' OR id IN (SELECT leadId FROM deliveries WHERE owner=? AND status IN ('Sent','Delivered'))),0) contacted FROM leads WHERE owner=?").bind(user,user).first<any>(),database.prepare('SELECT name FROM industries WHERE owner=? ORDER BY name').bind(user).all<any>(),database.prepare("SELECT c.*, (SELECT COUNT(*) FROM deliveries d WHERE d.campaignId=c.id) enrolled, (SELECT COUNT(*) FROM deliveries d WHERE d.campaignId=c.id AND d.status IN ('Sent','Delivered')) sent FROM campaigns c WHERE owner=? ORDER BY createdAt DESC LIMIT 200").bind(user).all(),database.prepare('SELECT r.*,l.name,l.email FROM replies r JOIN leads l ON l.id=r.leadId WHERE r.owner=? ORDER BY r.createdAt DESC LIMIT 200').bind(user).all(),getSettings(user)]);const replyCount=await database.prepare('SELECT COUNT(*) n FROM replies WHERE owner=?').bind(user).first<any>();const e=runtime();return Response.json({leads:list.results,total:count.n,stats:{...stats,replies:replyCount.n},industries:[...new Set(['Life Insurance','Hiring / Recruitment',...industry.results.map(r=>r.name)])],campaigns:campaigns.results,replies:replies.results,settings,connections:{leadApi:!!(e.LEAD_API_URL&&e.LEAD_API_KEY),email:!!(e.SENDGRID_API_KEY&&e.APP_URL&&e.UNSUBSCRIBE_SECRET),inbound:!!(e.INBOUND_WEBHOOK_SECRET||(e.SENDGRID_PARSE_PUBLIC_KEY&&e.INBOUND_REPLY_DOMAIN))}});}
 if(action==='saveLead'){const l=leadSchema.parse(d);l.email=l.email.toLowerCase();if(l.id){const existing=await database.prepare('SELECT * FROM leads WHERE id=? AND owner=?').bind(l.id,user).first<any>();if(!existing)throw new HttpError(404,'Lead not found');if(existing.status==='Unsubscribed'&&l.status!=='Unsubscribed')throw new HttpError(409,'Suppressed leads cannot be reactivated here.');const keys=Object.keys(l).filter(k=>k!=='id');try{await database.prepare(`UPDATE leads SET ${keys.map(k=>k+'=?').join(',')},updatedAt=? WHERE id=? AND owner=?`).bind(...keys.map(k=>k==='email'?(l.email||null):(l as any)[k]),now(),l.id,user).run();}catch(e:any){if(String(e).includes('UNIQUE'))throw new HttpError(409,'A lead with this email already exists');throw e;}}else{const result=await addLeads(user,[l]);if(!result.imported)throw new HttpError(409,'A lead with this email already exists');}if(l.status==='Unsubscribed')await suppress(user,l.email,'Manual unsubscribe');return Response.json({ok:true});}
 if(action==='import'){const rows=z.array(z.record(z.any())).min(1).max(1000).parse(d.rows);return Response.json(await addLeads(user,rows));}
 if(action==='bulkStatus'){const ids=z.array(id).min(1).max(1000).parse(d.ids);const status=z.enum(['New','Contacted','Interested','Not interested','Qualified']).parse(d.status);await database.batch(ids.map(i=>database.prepare("UPDATE leads SET status=?,updatedAt=? WHERE id=? AND owner=? AND status!='Unsubscribed'").bind(status,now(),i,user)));return Response.json({ok:true});}
 if(action==='addIndustry'){const name=text.parse(d.name);await database.prepare('INSERT INTO industries (id,owner,name) VALUES (?,?,?) ON CONFLICT(owner,name) DO NOTHING').bind(crypto.randomUUID(),user,name).run();return Response.json({ok:true});}
 if(action==='saveSettings'){const s=z.object({senderName:text,senderEmail:z.string().email(),replyTo:z.string().email(),postalAddress:z.string().trim().min(10).max(1000),dailyLimit:z.number().int().min(1).max(1000)}).parse(d);if(/[\r\n<>]/.test(s.senderName))throw new HttpError(400,'Invalid sender name');await database.prepare('INSERT INTO settings (owner,value) VALUES (?,?) ON CONFLICT(owner) DO UPDATE SET value=excluded.value').bind(user,JSON.stringify(s)).run();return Response.json({ok:true});}
 if(action==='saveCampaign'){const c=z.object({id:id.optional(),name:text,industry:text,subject:z.string().min(1).max(500),body:z.string().min(1).max(30000)}).parse(d);if(c.id){const sent=await database.prepare("SELECT COUNT(*) n FROM deliveries WHERE campaignId=? AND owner=? AND status!='Queued'").bind(c.id,user).first<any>();if(sent.n)throw new HttpError(409,'This campaign has started. Create a new campaign to change its message.');await database.prepare('UPDATE campaigns SET name=?,industry=?,subject=?,body=? WHERE id=? AND owner=?').bind(c.name,c.industry,c.subject,c.body,c.id,user).run();}else await database.prepare('INSERT INTO campaigns (id,owner,name,industry,subject,body,status,createdAt) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user,c.name,c.industry,c.subject,c.body,'Draft',now()).run();return Response.json({ok:true});}
 if(action==='enroll'){const campaignId=id.parse(d.campaignId),ids=z.array(id).min(1).max(1000).parse(d.leadIds);const c=await database.prepare('SELECT industry FROM campaigns WHERE id=? AND owner=?').bind(campaignId,user).first<any>();if(!c)throw new HttpError(404,'Campaign not found');let enrolled=0;for(let i=0;i<ids.length;i+=50){const results=await database.batch(ids.slice(i,i+50).map(leadId=>database.prepare("INSERT INTO deliveries (id,owner,campaignId,leadId,status,createdAt) SELECT ?,?,?,id,'Queued',? FROM leads WHERE id=? AND owner=? AND industry=? AND email IS NOT NULL AND permission!='Unknown' AND status!='Unsubscribed' AND NOT EXISTS(SELECT 1 FROM suppressions s WHERE s.owner=leads.owner AND s.email=leads.email) ON CONFLICT(campaignId,leadId) DO NOTHING").bind(crypto.randomUUID(),user,campaignId,now(),leadId,user,c.industry)));enrolled+=results.reduce((n,r)=>n+r.meta.changes,0);}return Response.json({enrolled,message:`${enrolled} eligible leads enrolled; duplicates, unpermissioned contacts and other industries excluded.`});}
 if(action==='activateCampaign'){const campaignId=id.parse(d.id);if(!runtime().SCHEDULER_SECRET)throw new HttpError(409,'Configure the external scheduler before activating automation.');const active=z.boolean().parse(d.active);await database.prepare('UPDATE campaigns SET status=? WHERE id=? AND owner=?').bind(active?'Active':'Paused',campaignId,user).run();return Response.json({message:active?'Automation enabled. Your configured scheduler will process this campaign.':'Campaign paused'});}
 if(action==='sendCampaign')return Response.json(await sendCampaign(user,id.parse(d.id)));
 if(action==='logReply'){const r=z.object({email:z.string().email(),subject:text,body:z.string().min(1).max(50000),classification}).parse(d);const lead=await database.prepare('SELECT id,email FROM leads WHERE owner=? AND email=?').bind(user,r.email.toLowerCase()).first<any>();if(!lead)throw new HttpError(404,'No lead found for that email');await database.prepare('INSERT INTO replies (id,owner,leadId,subject,body,classification,createdAt) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user,lead.id,r.subject,r.body,r.classification,now()).run();await applyClassification(user,lead.id,lead.email,r.classification);return Response.json({ok:true});}
 if(action==='classifyReply'){const replyId=id.parse(d.id),c=classification.parse(d.classification);const r=await database.prepare('SELECT r.leadId,l.email FROM replies r JOIN leads l ON l.id=r.leadId WHERE r.id=? AND r.owner=?').bind(replyId,user).first<any>();if(!r)throw new HttpError(404,'Reply not found');await database.prepare('UPDATE replies SET classification=? WHERE id=? AND owner=?').bind(c,replyId,user).run();await applyClassification(user,r.leadId,r.email,c);return Response.json({ok:true});}
 if(action==='generate'){const e=runtime();if(!e.LEAD_API_URL||!e.LEAD_API_KEY)throw new HttpError(409,'Connect a licensed data provider before generating leads.');const search=z.object({industry:text,state:text,type:text,city:z.string().max(300).default(''),query:z.string().max(300).default(''),limit:z.number().int().min(1).max(500)}).parse(d);const url=new URL(e.LEAD_API_URL);if(url.protocol!=='https:')throw new HttpError(503,'Provider URL must use HTTPS');const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${e.LEAD_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(search),signal:AbortSignal.timeout(25000),redirect:'error'});if(!r.ok)throw new HttpError(502,`Lead provider returned ${r.status}. Check credentials and plan limits.`);const result=await r.json() as any;if(!Array.isArray(result.leads)||result.leads.length>500)throw new HttpError(502,'Provider returned an invalid response');return Response.json(await addLeads(user,result.leads.map((l:any)=>({...l,industry:search.industry,type:l.type||search.type,source:l.source||'Licensed API'}))));}
 throw new HttpError(400,'Unknown action');
 }catch(e){return failure(e);}}
async function applyClassification(user:string,leadId:string,email:string,c:string){if(c==='Unsubscribe')return suppress(user,email,'Reply unsubscribe');if(c==='Interested'||c==='Not interested')await db().prepare("UPDATE leads SET status=?,updatedAt=? WHERE id=? AND owner=? AND status!='Unsubscribed'").bind(c,now(),leadId,user).run();}
